---
global:
  scrape_interval: 5s
  evaluation_interval: 5s

alerting:

rule_files:

scrape_configs:
  - job_name: weather-metrics-component
    static_configs:
      - targets: ["weather-metrics-component:8081"]
